import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>This is Blink</p>
        </div>

        <div className={styles.center}>
          <Image
            src="/blink.png"
            alt="Blink"
            width={640}
            height={640}
            priority
            style={{ borderRadius: "10px" }}
          />
        </div>
        <div className={styles.description}>
          <p>Blink is a Bunny and a Link.</p>
        </div>
        <div className={styles.description}>
          <p>
            He&apos;s the protector of web development law and living symbol of
            proper web element usage.
          </p>
        </div>
        <div className={styles.description}>
          <p>
            Every day he hops through the World Wide Web and keeps an eye on how
            developers use links and buttons.
          </p>
        </div>

        <div className={styles.center}>
          <Image
            src="/female_developer.png"
            alt="female developer"
            width={640}
            height={640}
            priority
            style={{ borderRadius: "10px" }}
          />
        </div>
        <div className={styles.description}>
          <p>
            Whenever a young developer is about to build a link that looks like
            a button, Blink is there to help.
          </p>
        </div>
        <div className={styles.description}>
          <p>
            Often he sees links dressed as buttons with attributes and styles
            they shouldn&apos;t have.
          </p>
        </div>
        <div className={styles.description}>
          <p>
            It&apos;s as if a bunny were pretending to be a T-Rex, a confusing
            sight!
          </p>
        </div>

        <div className={styles.center}>
          <Image
            src="/blink.png"
            alt="Blink"
            width={640}
            height={640}
            priority
            style={{ borderRadius: "10px" }}
          />
        </div>
        <div className={styles.description}>
          <p>
            Filled with wisdom gathered from his travels through HTML and CSS,
            Blink tells the developer never to confuse links and buttons.
          </p>
        </div>
        <div className={styles.description}>
          <p>
            To this day, Blink continues his journey, hopping and linking
            through the web, leaving behind a trail of well-coded websites.
          </p>
        </div>

        <div className={styles.center}>
          <Image
            src="/hugging.png"
            alt="developer and blink hugging"
            width={640}
            height={640}
            priority
            style={{ borderRadius: "10px" }}
          />
        </div>
        <div className={styles.description}>
          <p>
            The next time you see a link or a button, remember Blink, the cute
            little protector of the web.
          </p>
        </div>
      </main>
    </>
  );
}
